#%RAML 1.0 NamedExample
value: 

-
 artistId: 1
 artistName: Brainstorm
 genre: Pop

-
  artistId: 2
  artistName: Katie Melua 
  genre: Soul

-
  artistId: 3
  artistName: Beatles
  genre: Blues
   




